- name: Bash shell playbook
  hosts: apprentices
  tasks:
  - name: Docker PS
    shell: "docker ps"
    register: command_result
    args:
      executable: /bin/bash

  - debug: msg={{ command_result.stdout }}
