- name: Bash shell playbook
  hosts: localhost
  tasks:
  - name: Run shell command
    shell: id
    become_user: rwhitear
    register: command_result
    args:
      executable: /bin/bash

  - debug: msg={{ command_result.stdout }}
