- name: Bash shell playbook
  hosts: awx12
  tasks:
  - name: Run shell command
    shell: echo 'not a very good example.'
    register: command_result
    args:
      executable: /bin/bash

  - debug: msg={{ command_result.stdout }}
