- name: Bash shell playbook
  hosts: slightawx.uktme.cisco.com
  tasks:
  - name: Run shell command
    shell: "sudo rwhitear; whoami"
    become_user: rwhitear
    register: command_result
    args:
      executable: /bin/bash

  - debug: msg={{ command_result.stdout }}
