---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    towerhost: 10.52.249.125
    username: admin
    password: password

  tasks:

    - name: Check AWX jobs
      uri:
        url: "http://{{ towerhost }}/api/v2/jobs/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        status_code: 200,404
        timeout: 10
      register: tower_jobs

    - name: debug
      debug:
        var: tower_jobs
